language: python

python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python setup.py install
  - pip install -e ".[test]"
  - pip install tox-travis

script:
  - tox
